### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by blackforestcode** [stijnvanouplines/blade-country-flags#10]
Installation in conjunction with previously installed Filament PLugin "Filament Language Switch" fails:

```
Problem 1
    - stijnvanouplines/blade-country-flags[1.0.0, ..., 1.0.1] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - stijnvanouplines/blade-country-flags 1.0.2 requires illuminate/support ^8.0|^9.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires stijnvanouplines/blade-country-flags * -> satisfiable by stijnvanouplines/blade-country-flags[1.0.0, 1.0.1, 1.0.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require stijnvanouplines/blade-country-flags:*" to figure out if any version is installable, or "composer require stijnvanouplines/blade-country-flags:^2.1" if you know which you need.
```

Laravel Version:  10.3.3
Filament Version: 2.17.16
Filament Language Switch (bezhansalleh/filament-language-switch) Version: 1.0.6
PHP Version: 8.2.3
OS: WSL2 (Ubuntu 22.04.2 LTS) on Windows 11

**Comment by mahfoudfx** [comment]
Need update on Packagist to support Laravel 10.
Awaiting for the update, you can use this fork:  [cswni/blade-country-flags](https://github.com/cswni/blade-country-flags) which works perfectly with [Filament Language(Locale) Switcher](https://github.com/bezhanSalleh/filament-language-switch).

**Comment by blackforestcode** [comment]
Okay, please let me know when the update happened.

Thanks for sharing the fork!

**Comment by blackforestcode** [comment]
Thanks!
