### ISSUE TITLE
SY flag is wrong

### ISSUE THREAD

**Issue by nuernbergerA** [stijnvanouplines/blade-country-flags#2]
https://github.com/stijnvanouplines/blade-country-flags/blob/main/resources/svg/1x1-sy.svg
![image](https://user-images.githubusercontent.com/13331388/122445650-09bd8900-cfa2-11eb-830e-fe31993c9622.png)
vs 
![image](https://user-images.githubusercontent.com/13331388/122445760-25c12a80-cfa2-11eb-822d-2944c803fb9e.png)
https://en.wikipedia.org/wiki/Flag_of_Syria

**Comment by stijnvanouplines** [comment]
@nuernbergerA I fixed this, can you please check?
