### ISSUE TITLE
maybe it's a stupid question but...

### ISSUE THREAD

**Issue by boyfromhell** [stijnvanouplines/blade-country-flags#4]
Maybe the question is something stupid,
but how can i do such a thing?

`<x-flag-4x3-{{  $country->code }} class="w-6" />`

That is, to add a variable

edit
my solution

`{!! svg('flag-4x3-' . $val->country->code, ['class' => 'w-5'])->toHtml() !!}`

**Comment by rubenvanerk** [comment]
Try [dynamic components](https://laravel.com/docs/9.x/blade#dynamic-components)

**Comment by boyfromhell** [comment]
i made like this `{!! svg('flag-4x3-' . $val->country->code, ['class' => 'w-5'])->toHtml() !!}`

**Comment by warmwhisky** [comment]
> Try [dynamic components](https://laravel.com/docs/9.x/blade#dynamic-components)

I tried this way `<x-dynamic-component :component="'x-flag-4x3-'.$country->code" class="mt-4" />` but it's error was `Unable to locate a class or view for component [x-flag-4x3-af]`

However `<x-flag-4x3-af></x-flag-4x3-af>` works just fine.

**Comment by warmwhisky** [comment]
> Don't include the `x-` when you're creating a dynamic component, like so:
> 
> ```
> <x-dynamic-component :component="'flag-4x3-'.$country->code" class="mt-4" />
> ```

I tried your suggestion but unfortunately I get the same issue `Unable to locate a class or view for component [flag-4x3-af]`

I believe I am missing something here. Should all of the components be in my `/views/components` folder already? because they are not.

I tried your suggestion and I get the same issue `Unable to locate a class or view for component [flag-4x3-af]`

**Comment by rubenvanerk** [comment]
Just tried it on a fresh install and this works fine:
```blade
@php $code = 'af'; @endphp
<x-dynamic-component :component="'flag-4x3-' . $code" />
```

The components should _not_ be published to your `/views/components` folder.

**Comment by warmwhisky** [comment]
I was using the json from https://github.com/stijnvanouplines/blade-country-flags/issues/5#issuecomment-1318476927

When I iterated through them to show all flags it threw an error on the missing SVGs which I posted here https://github.com/stijnvanouplines/blade-country-flags/issues/5#issuecomment-1342746334

When using `{!! svg('flag-4x3-' . $val->country->code, ['class' => 'w-5'])->toHtml() !!}`  from https://github.com/stijnvanouplines/blade-country-flags/issues/4#issuecomment-1279409706 I was able to see the missing flags, but not determine in a clean way if they were missing
