### ISSUE TITLE
cn.svg is missing stars

### ISSUE THREAD

**Issue by codepuncher** [stijnvanouplines/blade-country-flags#6]
it seems that CN is pretty out of date with upstream.
Could it be updated, please?

This repo:
![https://raw.githubusercontent.com/stijnvanouplines/blade-country-flags/main/resources/svg/4x3-cn.svg](https://raw.githubusercontent.com/stijnvanouplines/blade-country-flags/main/resources/svg/4x3-cn.svg)

Upstream:
![https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/cn.svg](https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/cn.svg)

**Comment by qalainau** [comment]
It doesn't appear to be fixed.
Should I fork it?

**Comment by imnpc** [comment]
in 1.0.5 this flag is still wrong, no stars
